name: Run Cypress Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run cy:run

      - name: Generate HTML Report
        run: npm run generate-report # Ensure this script exists in package.json

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: cypress/reports/html/*.html # Adjust the path if necessary
          
      - name: List report files
        run: ls -la cypress/reports/
